In [10]:
l = [23245, 27,  546, 215, -1234]

In [11]:
import numpy as np

In [12]:
a = np. array(l)

In [13]:
a

array([23245,    27,   546,   215, -1234])

In [16]:
l.pop()

-1234

In [17]:
a.mean()

4559.8

In [18]:
l

[23245, 27, 546, 215]

In [19]:
l[0:2]

[23245, 27]

In [20]:
#------

In [21]:
a

array([23245,    27,   546,   215, -1234])

In [23]:
a[2:]

array([  546,   215, -1234])

In [24]:
b = a[2:4]

In [25]:
b

array([546, 215])

In [26]:
b[:] = 111

In [27]:
b

array([111, 111])

In [28]:
a

array([23245,    27,   111,   111, -1234])

In [29]:
c = a.copy()

In [30]:
c[0]=0

In [31]:
a

array([23245,    27,   111,   111, -1234])

In [33]:
l1 = [20, 'a', 21, 'b', 22, 'c', 23, 'd', 24, 'e', 25, 'f']

In [36]:
l1[-1:-12:-2]

['f', 'e', 'd', 'c', 'b', 'a']